### ISSUE TITLE
你把原来的demo整理很不错哦,后面的放出去的demo会借鉴你的方式哦~

### ISSUE THREAD

**Issue by sunbinbin1991** [liuky74/SDC-NNIE-tutorial#1]
Best wishes!

**Comment by yutao007** [comment]
大佬的这个demo太给力了，准备拿着个该yolov5算法加载到摄像机上看看。就不知道这中方式如何show出来。现在app都是通过sims查看的。

**Comment by liuky74** [comment]
> 大佬的这个demo太给力了，准备拿着个该yolov5算法加载到摄像机上看看。就不知道这中方式如何show出来。现在app都是通过sims查看的。

这个demo目前也是要通过sims show出来的,如果你不需要实时查看可以尝试用opencv保存视频和结果然后自己画上去也可以

**Comment by liuky74** [comment]
感谢来自官方的肯定

**Comment by CasonTsai** [comment]
@yutao007  请问大佬有推理yolov5的demo学习下么
