### ISSUE TITLE
关于part3里面的 ssd Demo里面的SVP_NNIE_FillForwardInfo,SVP_NNIE_Ssd_SoftmaxForward等函数疑问

### ISSUE THREAD

**Issue by CasonTsai** [liuky74/SDC-NNIE-tutorial#2]
![image](https://user-images.githubusercontent.com/18262642/118424857-943c6f80-b6fa-11eb-8464-c7d949dca532.png)
首先非常感谢大佬的tutorial,想问下这些函数是不是ssd的前处理和后处理，除了SAMPLE_SVP_NNIE_Forward是调用sdc的算法文件服务，剩余的是自己进行操作么，没有用到sdc的文件接口服务？

**Comment by liuky74** [comment]
的确是前后处理,还包括参数的初始化等等,除了forward调用了NNIE的接口外,前后处理都是自定义C++函数来操作的

**Comment by liuky74** [comment]
太长时间没看代码了,不是特别记得了,我印象中除了调用视频,加载模型和forward以外,就没有用sdc的文件接口了,后处理肯定是在C++中自定义的代码里完成的.

**Comment by CasonTsai** [comment]
好的，非常感谢大佬
