### ISSUE TITLE
关于第三个教程的疑问

### ISSUE THREAD

**Issue by CasonTsai** [liuky74/SDC-NNIE-tutorial#3]
您好，请问第三个教程钟设置一次性取12帧，推理时是相当于batch_size =12么，是不是转wk时要把batch_size参数设置为12？
还是说是一次性获取12帧，然后一帧一帧推理

**Comment by liuky74** [comment]
一次性取多少帧是单纯的字面上的意思,你需要从缓冲队列中一次性取出多少帧数据,默认的教程中应该是一次性只取1帧,每次推理1帧(教程中应该是只支持这样的,数据的导入都是根据内存地址写入,我应该没有写对于多batchSize的处理),
那个一次性取多少帧是我项目用的一个特殊功能,我在写教程的时候懒得改了,就原封不动的挪过来,你只要设置一次取1帧就可以正常运行.

**Comment by liuky74** [comment]
因此转wk的时候不需要改batch size=12,也不要用一次取多帧的功能,只取1帧就好了,除非你有修改模块以达到特殊功能的打算.

**Comment by CasonTsai** [comment]
嗯嗯，因为看到教程里面设置的是12，但是看获取推理时获取结果好像是处理一帧的，所以有点疑惑，，谢谢大佬
