### ISSUE TITLE
关于nnie yolov5的询问

### ISSUE THREAD

**Issue by wangxinRS** [liuky74/SDC-NNIE-tutorial#4]
大佬好。

请问，你准备写的nnie_yolov5的demo吗？

另外，PART3下的CMakeLists.txt能生成二进制文件吗？

**Comment by liuky74** [comment]
1.yolov5的一些算子,比如Focus应该NNIE还没有实现,能否自定义这个算子这个我不是很清楚,而且这个教程不涉及wk模型转换
2.Cmake文件生成二进制文件是什么意思?

**Comment by wangxinRS** [comment]
> 1.yolov5的一些算子,比如Focus应该NNIE还没有实现,能否自定义这个算子这个我不是很清楚,而且这个教程不涉及wk模型转换
> 2.Cmake文件生成二进制文件是什么意思?

**Comment by liuky74** [comment]
如果你是指生成可执行文件的话,可以的,生成的程序可以在摄像头上运行

**Comment by wangxinRS** [comment]
是这样的，华为好望角摄像头的算法移植过程中，有一步是要将c写的app（也就是你写的这个项目）转成二进制文件，然后再将二进制文件转成rpm文件，这个过程您接触过吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月10日(周五) 中午11:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liuky74/SDC-NNIE-tutorial] 关于nnie yolov5的询问 (#4)




 
1.yolov5的一些算子,比如Focus应该NNIE还没有实现,能否自定义这个算子这个我不是很清楚,而且这个教程不涉及wk模型转换
 2.Cmake文件生成二进制文件是什么意思?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangxinRS** [comment]
是这样的，我用华为好望角AI摄像头，现在想把自己的模型放进去，但是需要算法移植，这最后一步就是把C语言的SDC代码转成二进制文件，再生成rpm文件，这个过程你有实现吗

**Comment by liuky74** [comment]
你需要用华为提供给你的交叉编译平台进行编译,编译以后的二进制程序可以直接在摄像头上运行,打包就是基础的rpm打包,关于rpm打包这个随便搜一下就有了
这些都无关代码,是编译相关的知识,这个教程里并不包含的哦

**Comment by wangxinRS** [comment]
好的，感谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月10日(周五) 中午1:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [liuky74/SDC-NNIE-tutorial] 关于nnie yolov5的询问 (#4)




 
你需要用华为提供给你的交叉编译平台进行编译,编译以后的二进制程序可以直接在摄像头上运行,打包就是基础的rpm打包,关于rpm打包这个随便搜一下就有了
 这些都无关代码,是编译相关的知识,这个教程里并不包含的哦
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
