### ISSUE TITLE
海思静态库版本

### ISSUE THREAD

**Issue by dengxiongshi** [liuky74/SDC-NNIE-tutorial#6]
你好，你提供的海思静态库是哪种型号的，还是能够通用的

**Comment by liuky74** [comment]
静态库是官方提供的, 我使用的SDC芯片是hi3559, 最新版本可以找官方索要, 官方新版本的教程应该已经整合了我的代码, 本项目代码已经落后了.

**Comment by dengxiongshi** [comment]
好的，多谢。
